logging:
  level:
    org:
      springframework: ERROR
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://nelumbusdb1.cdwwk3jnhvz5.ap-south-1.rds.amazonaws.com/nelumbusdb    
    username: nelumbus
    password: '{cipher}ed4b66285a5f4b3dc44164fc4a91106bf83741b8be66a45e2bc69f4444140e84'
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://ec2-15-206-149-36.ap-south-1.compute.amazonaws.com:2222/eureka
